from openai import OpenAI
from app.config import NAVIGATE_BASE_URL, NAVIGATE_API_KEY, NAVIGATE_LLM_MODEL, NAVIGATE_STT_MODEL, NAVIGATE_TTS_MODEL

client = OpenAI(
    base_url=NAVIGATE_BASE_URL,
    api_key=NAVIGATE_API_KEY,
)

LLM_MODEL = NAVIGATE_LLM_MODEL
STT_MODEL = NAVIGATE_STT_MODEL
TTS_MODEL = NAVIGATE_TTS_MODEL
